// Generated by scripts/sync-manifest-config.mjs from apps/ai-markdown-studio-vs-community/config/command-metadata.json.

export const commandEntries = [
  { command: "markdownAiStudio.openPreview", title: "Open Preview" },
  { command: "markdownAiStudio.editAsText", title: "Edit Markdown" },
  { command: "markdownAiStudio.formatTables", title: "Format Tables" },
  { command: "markdownAiStudio.exportHtml", title: "Export: HTML" },
  { command: "markdownAiStudio.exportDocxBasic", title: "Export: DOCX (Basic)" },
  { command: "markdownAiStudio.generateDocument", title: "AI: Generate Document" },
  { command: "markdownAiStudio.generatePresentation", title: "AI: Generate Presentation" },
  { command: "markdownAiStudio.enableAiFeatures", title: "AI: Enable Features..." },
  { command: "markdownAiStudio.openSettings", title: "Change Settings..." },
  { command: "markdownAiStudio.toggleFrontMatter", title: "Toggle Frontmatter" },
] as const;
